PEP8 Dataloader filenames
antarctica/PolarRoute pull request #165
Opened 2023-04-05 11:25 UTC by hjabbot

Simple fix that updates filenames to be pep-8 compliant. Also had to change all the import statements to match the filenames, and also updated the docs to match too 

Here's the reg tests [passing](https://github.com/antarctica/PolarRoute/files/11158127/dl_rename_tests.txt) with the new filenames

2023-04-05 14:04 UTC, Ulvetanna commented on polar_route/__init__.py
Should this be for `VesselPerformanceModeller` not vessel_factory ?

2023-04-05 14:09 UTC, SamuelHall700 commented on polar_route/__init__.py
I think you're correct, I've added the VesselPerformanceModeller to the alias as well :)

2023-04-05 14:47 UTC, Ulvetanna requested changes
Looks good, but issue in the __init__.py where VesselFactory is defined over `vesselPerformanceModeller`

2023-04-05 15:30 UTC, SamuelHall700 commented on polar_route/__init__.py
^ I've added this in the alias as well

2023-04-10 13:24 UTC, Ulvetanna approved these changes
No issue then.

2023-04-11 08:13 UTC, merged