Mesh splitting on vectors
antarctica/PolarRoute pull request #185
Opened 2023-05-18 15:22 UTC by hjabbot

Date: 2023-05-17
Version Number: 0.2.3
 
## Description of change
Added multiple methods for calculating homogeneity conditions based on vector inputs. These methods include Curl, Divergence, Delta-Mag, and Reynolds number. These methods are detailed in the weekly meeting [summary](https://github.com/antarctica/SDADT-project/issues/39#issuecomment-1551366930)

After some testing, Curl appears to have the performance, both in computation time, and accuracy. The docs have been updated to show splitting conditions for Curl, but not the others which now only really exist to check for edge cases if the user wants to debug. These splitting conditions do not implement the `upper/lower_bound` idea that the scalar datasets use, with `get_hom_condition` producing 'HET' when above the curl threshold, 'CLR' when below, or 'MIN' when too few datapoints exist. I don't think that it would be wrong to adjust this to work with `upper/lower_bound`, but I don't see a use case for 'HOM' to exist for any currents/winds datasets. 

I have not created new tests for vector splitting, although I feel like that should be implemented ASAP. I can add that into this release if the reviewers request it, will just take another day or two. Alternatively to compartmentalise it, I can do that in a separate branch and PR.

Fixes 
[SDADT-project #123](https://github.com/antarctica/SDADT-project/issues/123)

# Testing
- [x] My changes result in all required regression tests passing without the need to update test files.  

> [Passing mesh-tests](https://github.com/antarctica/PolarRoute/files/11508934/pytest.txt)

- [ ] My changes require one or more test files to be updated for all regression tests to pass.   

> *include pytest.txt file showing which tests fail.*  
> *include reasoning as to why your changes cause these tests to fail.* 
>
> Should these changes be valid, relevant test files should be updated.  
> *include pytest.txt file of test passing after test files have been updated.*

# Checklist

- [x] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [x] I have commented my code, particularly in hard-to-understand areas.  
- [x] I have updated the documentation of the codebase where required.  
- [x] My changes generate no new warnings.   
- [x] My PR has been made to the `0.2.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

2023-05-19 08:28 UTC, ayat-khairy approved these changes
Nice work :)

2023-05-19 11:01 UTC, SamuelHall700 requested changes
The attached pytest.txt file contains only the following:
```
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/habbot/Documents/Work/PolarRoute
collected 84 items

test_mesh.py ........................................................... [ 70%]
.........................                                                [100%]

======================== 84 passed in 217.16s (0:03:37) ========================
```

Which doesn't include which of the tests have been run, verbose logging would have been nice - I've updated the PR template to request this in future. 

When attempting to run the tests of my branch - it crashed. This was due to a bug I'd introduced in my last PR. I've created a new PR now to fix it (https://github.com/antarctica/PolarRoute/pull/186) . Can the fix be pulled into this branch?

2023-05-22 10:05 UTC, SamuelHall700 approved these changes

2023-05-22 10:18 UTC, gecoombs approved these changes
All looks good to me!

2023-05-22 10:23 UTC, merged