Split cells when neighbouring inaccessible cells
antarctica/PolarRoute pull request #265
Opened 2024-03-26 11:05 UTC by gecoombs

# PolarRoute Pull Request

Date: 26/03 
Version Number: 0.3.14
 
## Description of change
Adds a method to the VesselPerformanceModeller that will split any cells neighbouring inaccessible cells (including land cells).

## Fixes #264 

# Testing
Files Changed:
```
polar_route/vessel_performance/vessel_performance_modeller.py
```

- [x] My changes require one or more test files to be updated for all regression tests to pass.   

Failing tests:
[vessel_test_results.txt](https://github.com/antarctica/PolarRoute/files/14757332/vessel_test_results.txt)

# Checklist

- [x] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [x] I have commented my code, particularly in hard-to-understand areas.  
- [x] I have updated the documentation of the codebase where required.  
- [x] My changes generate no new warnings.   
- [ ] My PR has been made to the `0.3.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

2024-03-26 11:12 UTC, gecoombs commented
This PR causes various regression tests to fail as the additional splitting modifies the vessel performance mesh and its neighbour graph. I have not updated the test files on this branch yet as the final changes @Ulvetanna needs to make to resolve [the issue with splitting around waypoints](https://github.com/antarctica/MeshiPhi/issues/39) will also require changing the tests and it may be easier to roll all of these changes into one big update.

2024-03-26 11:23 UTC, gecoombs commented
Difference in the meshes for the `grf_normal` mesh from the regression test examples:

Reference mesh:
![Screenshot from 2024-03-26 11-20-35](https://github.com/antarctica/PolarRoute/assets/96303082/36e13a64-fea5-44ac-9b59-235b3bc99f67)

New mesh:
![Screenshot from 2024-03-26 11-20-45](https://github.com/antarctica/PolarRoute/assets/96303082/39c74184-ddff-4e5c-986d-e27886b1ae14)

2024-03-26 13:55 UTC, gecoombs commented
I have now modified the vessel performance regression test files to match this version of the code as any further changes related to waypoint splitting will only change the route planning test results.

2024-03-27 13:25 UTC, SamuelHall700 approved these changes
Looks good!

2024-03-27 14:06 UTC, Ulvetanna requested changes
Add in the get_height(), don't only consider on the get_width alone 👍

2024-03-27 14:06 UTC, Ulvetanna commented on polar_route/vessel_performance/vessel_performance_modeller.py
> +            while any(neighbour.boundary.get_width() > in_cb.boundary.get_width() for neighbour in acc_neighbours):
Could we have this more generalisable for the get_width and get_height. I think in our splitting at the moment it is ok, but may create an issues later :)

2024-04-10 07:58 UTC, Ulvetanna approved these changes
Thanks for adding the addition for cell height ! All good to go

2024-04-10 12:05 UTC, merged