PolarRoute - New Vehicles - BoatyMcBoatFace, TwinOtter & Windracers
antarctica/PolarRoute pull request #268
Opened 2024-04-10 08:40 UTC by Ulvetanna

# PolarRoute Pull Request Template

Date:    
Version Number:    
 
## Description of change

## Fixes # (issue)

# Testing
To ensure that the functionality of the PolarRoute codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 

- [ ] My changes have not altered any of the files listed in the testing strategy

- [ ] My changes result in all required regression tests passing without the need to update test files.  
  
> *list which files have been altered and include a pytest.txt file for each of
> the tests required to be run*
>
> The files which have been changed during this PR can be listed using the command

    git diff --name-only 0.3.x

- [ ] My changes require one or more test files to be updated for all regression tests to pass.   

> *include pytest.txt file showing which tests fail.*  
> *include reasoning as to why your changes cause these tests to fail.* 
>
> Should these changes be valid, relevant test files should be updated.  
> *include pytest.txt file of test passing after test files have been updated.*

# Checklist

- [ ] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [ ] I have commented my code, particularly in hard-to-understand areas.  
- [ ] I have updated the documentation of the codebase where required.  
- [ ] My changes generate no new warnings.   
- [ ] My PR has been made to the `0.3.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

2024-04-10 09:44 UTC, gecoombs requested changes
Generally looks good and nice to see the extension of the vessel performance models with new types of vehicle. Unless there's a good reason to keep them separate I think you should merge the abstract classes for the planes/UAVs to avoid duplication of code. You can add any specific differences in the implemented classes for each vehicle. Otherwise just a few comments on naming/formatting/docstrings etc.

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessel_factory.py
> +                               "Windracer": (Windracer, ["max_speed", "unit","max_ice_conc", "min_depth"]),
Change "min_depth" to "max_elevation" as this about obstacle avoidance not water depth.

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_glider.py
> +        access_values['land']    = self.land(cellbox)
Not sure why this needed to be changed, VS code auto-formatting? PEP8 recommends one space either side of assignment operators: https://peps.python.org/pep-0008/#pet-peeves

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        self.max_elevation  = -1 * self.vessel_params['min_depth']
Remove this factor of -1 for planes/aerial drones and just specify max elevation in the config

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        access_values['shallow'] = self.shallow(cellbox)
Change the name of 'shallow' here to something that makes more sense in context. Maybe "elevated terrain"? Could try to find something more concise.

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        Abstract class to model the performance of an underwater glider
Update docstring to reference planes not gliders.

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +            Method to determine if a given cell is accessible to the underwater glider
Again update docstring

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +            Method to determine the performance characteristics for the underwater glider
Docstring update

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        access_values['land']    = self.land(cellbox)
As I understand it, this will mark all land as inaccessible to any plane which isn't what you would want surely?

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +    def shallow(self, cellbox):
Update the name "shallow" here as well as the docstring

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_uav.py
Do you need separate abstract classes for aerial drones and planes? I think you could just have one abstract aerial vehicle class and then specific implementations for drones/planes, to avoid duplication.

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/boatymcboatface.py
> +
Remove blank lines before imports

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/boatymcboatface.py
> +            Method to determine the maximum speed that the glider can traverse the given cell
An ALR, not a glider

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/slocum.py
> +        depth_coefficients    = np.array([0.001, 2])
Revert as above (pep8 and spacing)

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/twin_otter.py
> +            Method to determine the maximum speed that the glider can traverse the given cell
Update docstring as above

2024-04-10 09:44 UTC, gecoombs commented on polar_route/vessel_performance/vessels/windracer.py
> +            Method to determine the maximum speed that the glider can traverse the given cell
Update docstring

2024-04-10 12:15 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        access_values['land']    = self.land(cellbox)
You're right, my mistake :+1:

2024-04-10 12:19 UTC, Ulvetanna commented
All changes have been resolved above @gecoombs can you take a second look just incase.

2024-04-10 12:27 UTC, gecoombs commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        self.max_elevation  = self.vessel_params['min_elevation']
'min_elevation' -> 'max_elevation'

2024-04-10 12:32 UTC, Ulvetanna commented on polar_route/vessel_performance/vessels/abstract_plane.py
> +        self.max_elevation  = self.vessel_params['min_elevation']
Sorry didn't commit the change (:

2024-04-10 12:40 UTC, gecoombs commented
> > Generally looks good and nice to see the extension of the vessel performance models with new types of vehicle. Unless there's a good reason to keep them separate I think you should merge the abstract classes for the planes/UAVs to avoid duplication of code. You can add any specific differences in the implemented classes for each vehicle. Otherwise just a few comments on naming/formatting/docstrings etc.
> 
> I concur, and on that point... is there a reason that none of the functions are defined in the `abstract_vessel.py` @gecoombs ? Is it set up to be an interface like `dataloader_interface.py`? e.g. `land()` defined in `abstract_ship()` is generic and reads from the config, I don't see why this would be different for any other vessel, and hence why it wouldn't be in `abstract_vessel.py`

It was quite a while ago now but yeah I think I based the structure on what had been done as part of the previous refactor for the dataloaders etc. although I'm open to the suggestion that this interface structure isn't necessarily required or could be renamed. Any change for that purpose is probably outside the scope of this pull request though.

2024-04-11 10:05 UTC, gecoombs commented on polar_route/vessel_performance/vessels/windracer.py
> +    def model_battery(self, cellbox):
The power output here is generated by a set of twin petrol fuelled engines, not drawn from a battery. See e.g. https://www.flightglobal.com/civil-uavs/british-antarctic-survey-readies-for-future-as-it-prepares-for-ultra-uav-trials/155603.article

2024-04-11 13:52 UTC, merged